// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import LoadingLayout from "@/app/LoadingLayout";
// import "./globals.css";
// import "./chef-theme.css";
// import Navbar from "@/components/navbar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <LoadingLayout>
//           <Navbar/>
//           {children}
//           </LoadingLayout>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import LoadingLayout from "@/app/LoadingLayout";
import "./globals.css";
import "./chef-theme.css";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoadingLayout>
          <Navbar />
          {/*
            Add padding-top to the main content area.
            This prevents the page content from being obscured by the fixed navbar.
            Calculated navbar height: 
            1rem (nav_padding_top) + 2.5rem (logo_line_height) + 1rem (nav_padding_bottom) + 2px (border_bottom) 
            = 4.5rem + 2px = (72px + 2px) = 74px.
            Using pt-[74px] for Tailwind's JIT compiler.
          */}
          <main className="pt-[74px]">
            {children}
          </main>
        </LoadingLayout>
      </body>
    </html>
  );
}